{"level":"error","message":"Logging in failed: User not found","stack":"Error: User not found\n    at Login$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/auth.js:47:13)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:145:13","timestamp":"2020-03-09 14:39:04"}
{"message":"error creating reward for level:innyLeveLZaCzystaInoRoz","level":"error","timestamp":"2020-03-12 17:00:42"}
{"level":"error","timestamp":"2020-03-12 17:00:42","message":"Cannot read property 'gt' of undefined","stack":"TypeError: Cannot read property 'gt' of undefined\n    at _callee$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:65:29)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:170:11\n    at new Promise (<anonymous>)\n    at callInvokeWithMethodAndArg (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:169:16)\n    at AsyncIterator.enqueue (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:192:13)\n    at AsyncIterator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at Object.exports.async (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:216:14)\n    at forEach (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:59:26)\n    at Array.forEach (<anonymous>)\n    at GenerateRewards$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:59:18)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:145:13"}
{"message":"error creating reward for level:testLevelZaStowe","level":"error","timestamp":"2020-03-12 17:00:42"}
{"level":"error","timestamp":"2020-03-12 17:00:42","message":"Cannot read property 'gt' of undefined","stack":"TypeError: Cannot read property 'gt' of undefined\n    at _callee$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:65:29)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:170:11\n    at new Promise (<anonymous>)\n    at callInvokeWithMethodAndArg (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:169:16)\n    at AsyncIterator.enqueue (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:192:13)\n    at AsyncIterator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at Object.exports.async (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:216:14)\n    at forEach (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:59:26)\n    at Array.forEach (<anonymous>)\n    at GenerateRewards$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:59:18)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:145:13"}
{"message":"error creating reward for level:innyLeveLZaCzystaInoRoz","level":"error","timestamp":"2020-03-12 17:02:17"}
{"level":"error","timestamp":"2020-03-12 17:02:17","message":"Cannot read property 'gt' of undefined","stack":"TypeError: Cannot read property 'gt' of undefined\n    at _callee$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:67:19)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:170:11\n    at new Promise (<anonymous>)\n    at callInvokeWithMethodAndArg (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:169:16)\n    at AsyncIterator.enqueue (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:192:13)\n    at AsyncIterator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at Object.exports.async (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:216:14)\n    at forEach (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:61:26)\n    at Array.forEach (<anonymous>)\n    at GenerateRewards$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:61:18)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:145:13"}
{"message":"error creating reward for level:testLevelZaStowe","level":"error","timestamp":"2020-03-12 17:02:17"}
{"level":"error","timestamp":"2020-03-12 17:02:17","message":"Cannot read property 'gt' of undefined","stack":"TypeError: Cannot read property 'gt' of undefined\n    at _callee$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:67:19)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:170:11\n    at new Promise (<anonymous>)\n    at callInvokeWithMethodAndArg (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:169:16)\n    at AsyncIterator.enqueue (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:192:13)\n    at AsyncIterator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at Object.exports.async (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:216:14)\n    at forEach (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:61:26)\n    at Array.forEach (<anonymous>)\n    at GenerateRewards$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:61:18)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:145:13"}
{"message":"error creating reward for level:innyLeveLZaCzystaInoRoz","level":"error","timestamp":"2020-03-12 17:08:37"}
{"name":"SequelizeDatabaseError","parent":{"name":"error","length":507,"severity":"BŁĄD","code":"22007","internalPosition":"159","internalQuery":"INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'innyLeveLZaCzystaInoRoz  1-function getFullYear() { [native code] }',2,'Invalid date','2020-03-12 16:08:37.138 +00:00') RETURNING *","where":"funkcja PL/pgSQL pg_temp_8.testfunc(), wiersz 1 w wyrażenie SQL","file":"d:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\datetime.c","line":"3774","routine":"DateTimeParseError","sql":"CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"rewards\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_7e958e62c845476b992c8028c3a0be37$ BEGIN INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'innyLeveLZaCzystaInoRoz  1-function getFullYear() { [native code] }',2,'Invalid date','2020-03-12 16:08:37.138 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_7e958e62c845476b992c8028c3a0be37$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"},"original":{"name":"error","length":507,"severity":"BŁĄD","code":"22007","internalPosition":"159","internalQuery":"INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'innyLeveLZaCzystaInoRoz  1-function getFullYear() { [native code] }',2,'Invalid date','2020-03-12 16:08:37.138 +00:00') RETURNING *","where":"funkcja PL/pgSQL pg_temp_8.testfunc(), wiersz 1 w wyrażenie SQL","file":"d:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\datetime.c","line":"3774","routine":"DateTimeParseError","sql":"CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"rewards\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_7e958e62c845476b992c8028c3a0be37$ BEGIN INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'innyLeveLZaCzystaInoRoz  1-function getFullYear() { [native code] }',2,'Invalid date','2020-03-12 16:08:37.138 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_7e958e62c845476b992c8028c3a0be37$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"},"sql":"CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"rewards\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_7e958e62c845476b992c8028c3a0be37$ BEGIN INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'innyLeveLZaCzystaInoRoz  1-function getFullYear() { [native code] }',2,'Invalid date','2020-03-12 16:08:37.138 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_7e958e62c845476b992c8028c3a0be37$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();","level":"error","timestamp":"2020-03-12 17:08:37","message":"nieprawidłowa składnia wejścia dla typu timestamp with time zone: \"Invalid date\"","stack":"SequelizeDatabaseError: nieprawidłowa składnia wejścia dla typu timestamp with time zone: \"Invalid date\"\n    at Query.formatError (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:366:16)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:72:18\nFrom previous event:\n    at Query.run (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:64:23)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:645:29\nFrom previous event:\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:645:12\nFrom previous event:\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:641:10\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\retry-as-promised\\index.js:70:21\n    at new Promise (<anonymous>)\n    at retryAsPromised (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\retry-as-promised\\index.js:60:10)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:631:30\nFrom previous event:\n    at Sequelize.query (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:580:23)\n    at QueryInterface.insert (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\query-interface.js:885:27)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:3985:52\nFrom previous event:\n    at model.save (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:3962:8)\n    at Function.create (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2226:8)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2332:19\n    at processImmediate (internal/timers.js:439:21)\n    at process.topLevelDomainCallback (domain.js:130:23)\nFrom previous event:\n    at Function.findOrCreate (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2320:8)\n    at _callee$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:64:44)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:170:11\n    at new Promise (<anonymous>)\n    at callInvokeWithMethodAndArg (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:169:16)\n    at AsyncIterator.enqueue (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:192:13)\n    at AsyncIterator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at Object.exports.async (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:216:14)\n    at forEach (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:61:26)\n    at Array.forEach (<anonymous>)\n    at GenerateRewards$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:61:18)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:145:13"}
{"message":"error creating reward for level:testLevelZaStowe","level":"error","timestamp":"2020-03-12 17:08:38"}
{"name":"SequelizeDatabaseError","parent":{"name":"error","length":500,"severity":"BŁĄD","code":"22007","internalPosition":"152","internalQuery":"INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'testLevelZaStowe  1-function getFullYear() { [native code] }',1,'Invalid date','2020-03-12 16:08:37.849 +00:00') RETURNING *","where":"funkcja PL/pgSQL pg_temp_9.testfunc(), wiersz 1 w wyrażenie SQL","file":"d:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\datetime.c","line":"3774","routine":"DateTimeParseError","sql":"CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"rewards\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_3b4ca74c7d0e486bbdeb218d405dc388$ BEGIN INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'testLevelZaStowe  1-function getFullYear() { [native code] }',1,'Invalid date','2020-03-12 16:08:37.849 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_3b4ca74c7d0e486bbdeb218d405dc388$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"},"original":{"name":"error","length":500,"severity":"BŁĄD","code":"22007","internalPosition":"152","internalQuery":"INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'testLevelZaStowe  1-function getFullYear() { [native code] }',1,'Invalid date','2020-03-12 16:08:37.849 +00:00') RETURNING *","where":"funkcja PL/pgSQL pg_temp_9.testfunc(), wiersz 1 w wyrażenie SQL","file":"d:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\datetime.c","line":"3774","routine":"DateTimeParseError","sql":"CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"rewards\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_3b4ca74c7d0e486bbdeb218d405dc388$ BEGIN INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'testLevelZaStowe  1-function getFullYear() { [native code] }',1,'Invalid date','2020-03-12 16:08:37.849 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_3b4ca74c7d0e486bbdeb218d405dc388$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"},"sql":"CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"rewards\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_3b4ca74c7d0e486bbdeb218d405dc388$ BEGIN INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'testLevelZaStowe  1-function getFullYear() { [native code] }',1,'Invalid date','2020-03-12 16:08:37.849 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_3b4ca74c7d0e486bbdeb218d405dc388$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();","level":"error","timestamp":"2020-03-12 17:08:38","message":"nieprawidłowa składnia wejścia dla typu timestamp with time zone: \"Invalid date\"","stack":"SequelizeDatabaseError: nieprawidłowa składnia wejścia dla typu timestamp with time zone: \"Invalid date\"\n    at Query.formatError (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:366:16)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:72:18\nFrom previous event:\n    at Query.run (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:64:23)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:645:29\nFrom previous event:\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:645:12\nFrom previous event:\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:641:10\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\retry-as-promised\\index.js:70:21\n    at new Promise (<anonymous>)\n    at retryAsPromised (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\retry-as-promised\\index.js:60:10)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:631:30\nFrom previous event:\n    at Sequelize.query (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:580:23)\n    at QueryInterface.insert (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\query-interface.js:885:27)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:3985:52\nFrom previous event:\n    at model.save (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:3962:8)\n    at Function.create (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2226:8)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2332:19\n    at processImmediate (internal/timers.js:439:21)\n    at process.topLevelDomainCallback (domain.js:130:23)\nFrom previous event:\n    at Function.findOrCreate (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2320:8)\n    at _callee$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:64:44)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:170:11\n    at new Promise (<anonymous>)\n    at callInvokeWithMethodAndArg (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:169:16)\n    at AsyncIterator.enqueue (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:192:13)\n    at AsyncIterator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at Object.exports.async (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:216:14)\n    at forEach (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:61:26)\n    at Array.forEach (<anonymous>)\n    at GenerateRewards$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:61:18)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:145:13"}
{"message":"error creating reward for level:innyLeveLZaCzystaInoRoz","level":"error","timestamp":"2020-03-12 17:10:26"}
{"name":"SequelizeDatabaseError","parent":{"name":"error","length":471,"severity":"BŁĄD","code":"22007","internalPosition":"123","internalQuery":"INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'innyLeveLZaCzystaInoRoz  1-2020',2,'Invalid date','2020-03-12 16:10:26.593 +00:00') RETURNING *","where":"funkcja PL/pgSQL pg_temp_8.testfunc(), wiersz 1 w wyrażenie SQL","file":"d:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\datetime.c","line":"3774","routine":"DateTimeParseError","sql":"CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"rewards\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_043c196b6baa4c04a462b8e774d76208$ BEGIN INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'innyLeveLZaCzystaInoRoz  1-2020',2,'Invalid date','2020-03-12 16:10:26.593 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_043c196b6baa4c04a462b8e774d76208$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"},"original":{"name":"error","length":471,"severity":"BŁĄD","code":"22007","internalPosition":"123","internalQuery":"INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'innyLeveLZaCzystaInoRoz  1-2020',2,'Invalid date','2020-03-12 16:10:26.593 +00:00') RETURNING *","where":"funkcja PL/pgSQL pg_temp_8.testfunc(), wiersz 1 w wyrażenie SQL","file":"d:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\datetime.c","line":"3774","routine":"DateTimeParseError","sql":"CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"rewards\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_043c196b6baa4c04a462b8e774d76208$ BEGIN INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'innyLeveLZaCzystaInoRoz  1-2020',2,'Invalid date','2020-03-12 16:10:26.593 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_043c196b6baa4c04a462b8e774d76208$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"},"sql":"CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"rewards\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_043c196b6baa4c04a462b8e774d76208$ BEGIN INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'innyLeveLZaCzystaInoRoz  1-2020',2,'Invalid date','2020-03-12 16:10:26.593 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_043c196b6baa4c04a462b8e774d76208$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();","level":"error","timestamp":"2020-03-12 17:10:26","message":"nieprawidłowa składnia wejścia dla typu timestamp with time zone: \"Invalid date\"","stack":"SequelizeDatabaseError: nieprawidłowa składnia wejścia dla typu timestamp with time zone: \"Invalid date\"\n    at Query.formatError (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:366:16)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:72:18\nFrom previous event:\n    at Query.run (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:64:23)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:645:29\nFrom previous event:\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:645:12\nFrom previous event:\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:641:10\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\retry-as-promised\\index.js:70:21\n    at new Promise (<anonymous>)\n    at retryAsPromised (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\retry-as-promised\\index.js:60:10)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:631:30\nFrom previous event:\n    at Sequelize.query (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:580:23)\n    at QueryInterface.insert (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\query-interface.js:885:27)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:3985:52\nFrom previous event:\n    at model.save (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:3962:8)\n    at Function.create (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2226:8)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2332:19\n    at processImmediate (internal/timers.js:439:21)\n    at process.topLevelDomainCallback (domain.js:130:23)\nFrom previous event:\n    at Function.findOrCreate (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2320:8)\n    at _callee$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:64:44)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:170:11\n    at new Promise (<anonymous>)\n    at callInvokeWithMethodAndArg (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:169:16)\n    at AsyncIterator.enqueue (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:192:13)\n    at AsyncIterator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at Object.exports.async (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:216:14)\n    at forEach (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:61:26)\n    at Array.forEach (<anonymous>)\n    at GenerateRewards$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:61:18)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:145:13"}
{"message":"error creating reward for level:testLevelZaStowe","level":"error","timestamp":"2020-03-12 17:10:27"}
{"name":"SequelizeDatabaseError","parent":{"name":"error","length":464,"severity":"BŁĄD","code":"22007","internalPosition":"116","internalQuery":"INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'testLevelZaStowe  1-2020',1,'Invalid date','2020-03-12 16:10:26.980 +00:00') RETURNING *","where":"funkcja PL/pgSQL pg_temp_9.testfunc(), wiersz 1 w wyrażenie SQL","file":"d:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\datetime.c","line":"3774","routine":"DateTimeParseError","sql":"CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"rewards\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_3f50fff428224c94872d56f31c1f4ff2$ BEGIN INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'testLevelZaStowe  1-2020',1,'Invalid date','2020-03-12 16:10:26.980 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_3f50fff428224c94872d56f31c1f4ff2$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"},"original":{"name":"error","length":464,"severity":"BŁĄD","code":"22007","internalPosition":"116","internalQuery":"INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'testLevelZaStowe  1-2020',1,'Invalid date','2020-03-12 16:10:26.980 +00:00') RETURNING *","where":"funkcja PL/pgSQL pg_temp_9.testfunc(), wiersz 1 w wyrażenie SQL","file":"d:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\datetime.c","line":"3774","routine":"DateTimeParseError","sql":"CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"rewards\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_3f50fff428224c94872d56f31c1f4ff2$ BEGIN INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'testLevelZaStowe  1-2020',1,'Invalid date','2020-03-12 16:10:26.980 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_3f50fff428224c94872d56f31c1f4ff2$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"},"sql":"CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"rewards\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_3f50fff428224c94872d56f31c1f4ff2$ BEGIN INSERT INTO \"rewards\" (\"id\",\"name\",\"levelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'testLevelZaStowe  1-2020',1,'Invalid date','2020-03-12 16:10:26.980 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_3f50fff428224c94872d56f31c1f4ff2$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();","level":"error","timestamp":"2020-03-12 17:10:27","message":"nieprawidłowa składnia wejścia dla typu timestamp with time zone: \"Invalid date\"","stack":"SequelizeDatabaseError: nieprawidłowa składnia wejścia dla typu timestamp with time zone: \"Invalid date\"\n    at Query.formatError (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:366:16)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:72:18\nFrom previous event:\n    at Query.run (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:64:23)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:645:29\nFrom previous event:\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:645:12\nFrom previous event:\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:641:10\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\retry-as-promised\\index.js:70:21\n    at new Promise (<anonymous>)\n    at retryAsPromised (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\retry-as-promised\\index.js:60:10)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:631:30\nFrom previous event:\n    at Sequelize.query (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:580:23)\n    at QueryInterface.insert (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\query-interface.js:885:27)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:3985:52\nFrom previous event:\n    at model.save (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:3962:8)\n    at Function.create (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2226:8)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2332:19\n    at processImmediate (internal/timers.js:439:21)\n    at process.topLevelDomainCallback (domain.js:130:23)\nFrom previous event:\n    at Function.findOrCreate (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2320:8)\n    at _callee$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:64:44)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:170:11\n    at new Promise (<anonymous>)\n    at callInvokeWithMethodAndArg (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:169:16)\n    at AsyncIterator.enqueue (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:192:13)\n    at AsyncIterator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at Object.exports.async (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:216:14)\n    at forEach (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:61:26)\n    at Array.forEach (<anonymous>)\n    at GenerateRewards$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/todo.js:61:18)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:145:13"}
{"message":"error creating reward for level:innyLeveLZaCzystaInoRoz","level":"error","timestamp":"2020-03-16 16:02:22"}
{"name":"SequelizeDatabaseError","parent":{"name":"error","length":221,"severity":"BŁĄD","code":"22007","position":"141","file":"d:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\datetime.c","line":"3774","routine":"DateTimeParseError","sql":"SELECT \"id\", \"name\", \"levelId\", \"createdAt\", \"updatedAt\" FROM \"rewards\" AS \"reward\" WHERE \"reward\".\"levelId\" = 2 AND \"reward\".\"createdAt\" > 'Invalid date' LIMIT 1;"},"original":{"name":"error","length":221,"severity":"BŁĄD","code":"22007","position":"141","file":"d:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\datetime.c","line":"3774","routine":"DateTimeParseError","sql":"SELECT \"id\", \"name\", \"levelId\", \"createdAt\", \"updatedAt\" FROM \"rewards\" AS \"reward\" WHERE \"reward\".\"levelId\" = 2 AND \"reward\".\"createdAt\" > 'Invalid date' LIMIT 1;"},"sql":"SELECT \"id\", \"name\", \"levelId\", \"createdAt\", \"updatedAt\" FROM \"rewards\" AS \"reward\" WHERE \"reward\".\"levelId\" = 2 AND \"reward\".\"createdAt\" > 'Invalid date' LIMIT 1;","level":"error","timestamp":"2020-03-16 16:02:22","message":"nieprawidłowa składnia wejścia dla typu timestamp with time zone: \"Invalid date\"","stack":"SequelizeDatabaseError: nieprawidłowa składnia wejścia dla typu timestamp with time zone: \"Invalid date\"\n    at Query.formatError (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:366:16)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:72:18\nFrom previous event:\n    at Query.run (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:64:23)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:645:29\nFrom previous event:\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:645:12\nFrom previous event:\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:641:10\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\retry-as-promised\\index.js:70:21\n    at new Promise (<anonymous>)\n    at retryAsPromised (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\retry-as-promised\\index.js:60:10)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:631:30\nFrom previous event:\n    at Sequelize.query (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:580:23)\n    at QueryInterface.select (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\query-interface.js:1121:27)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:1757:34\nFrom previous event:\n    at Function.findAll (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:1755:8)\n    at Function.findOne (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:1924:17)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2319:19\n    at processImmediate (internal/timers.js:439:21)\n    at process.topLevelDomainCallback (domain.js:130:23)\nFrom previous event:\n    at Function.findOrCreate (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2315:48)\n    at _callee$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/rewardGenerator.js:41:44)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:170:11\n    at new Promise (<anonymous>)\n    at callInvokeWithMethodAndArg (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:169:16)\n    at AsyncIterator.enqueue (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:192:13)\n    at AsyncIterator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at Object.exports.async (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:216:14)\n    at forEach (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/rewardGenerator.js:37:26)\n    at Array.forEach (<anonymous>)\n    at GenerateRewards$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/rewardGenerator.js:37:18)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:145:13"}
{"message":"error creating reward for level:testLevelZaStowe","level":"error","timestamp":"2020-03-16 16:02:23"}
{"name":"SequelizeDatabaseError","parent":{"name":"error","length":221,"severity":"BŁĄD","code":"22007","position":"141","file":"d:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\datetime.c","line":"3774","routine":"DateTimeParseError","sql":"SELECT \"id\", \"name\", \"levelId\", \"createdAt\", \"updatedAt\" FROM \"rewards\" AS \"reward\" WHERE \"reward\".\"levelId\" = 1 AND \"reward\".\"createdAt\" > 'Invalid date' LIMIT 1;"},"original":{"name":"error","length":221,"severity":"BŁĄD","code":"22007","position":"141","file":"d:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\datetime.c","line":"3774","routine":"DateTimeParseError","sql":"SELECT \"id\", \"name\", \"levelId\", \"createdAt\", \"updatedAt\" FROM \"rewards\" AS \"reward\" WHERE \"reward\".\"levelId\" = 1 AND \"reward\".\"createdAt\" > 'Invalid date' LIMIT 1;"},"sql":"SELECT \"id\", \"name\", \"levelId\", \"createdAt\", \"updatedAt\" FROM \"rewards\" AS \"reward\" WHERE \"reward\".\"levelId\" = 1 AND \"reward\".\"createdAt\" > 'Invalid date' LIMIT 1;","level":"error","timestamp":"2020-03-16 16:02:23","message":"nieprawidłowa składnia wejścia dla typu timestamp with time zone: \"Invalid date\"","stack":"SequelizeDatabaseError: nieprawidłowa składnia wejścia dla typu timestamp with time zone: \"Invalid date\"\n    at Query.formatError (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:366:16)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:72:18\nFrom previous event:\n    at Query.run (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:64:23)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:645:29\nFrom previous event:\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:645:12\nFrom previous event:\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:641:10\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\retry-as-promised\\index.js:70:21\n    at new Promise (<anonymous>)\n    at retryAsPromised (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\retry-as-promised\\index.js:60:10)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:631:30\nFrom previous event:\n    at Sequelize.query (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\sequelize.js:580:23)\n    at QueryInterface.select (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\query-interface.js:1121:27)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:1757:34\nFrom previous event:\n    at Function.findAll (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:1755:8)\n    at Function.findOne (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:1924:17)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2319:19\n    at processImmediate (internal/timers.js:439:21)\n    at process.topLevelDomainCallback (domain.js:130:23)\nFrom previous event:\n    at Function.findOrCreate (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\sequelize\\lib\\model.js:2315:48)\n    at _callee$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/rewardGenerator.js:41:44)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:170:11\n    at new Promise (<anonymous>)\n    at callInvokeWithMethodAndArg (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:169:16)\n    at AsyncIterator.enqueue (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:192:13)\n    at AsyncIterator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at Object.exports.async (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:216:14)\n    at forEach (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/rewardGenerator.js:37:26)\n    at Array.forEach (<anonymous>)\n    at GenerateRewards$ (E:\\hateemel\\projects\\node\\patron-helper\\src\\services/rewardGenerator.js:37:18)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at Generator.invoke [as _invoke] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n    at tryCatch (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n    at invoke (E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:135:20)\n    at E:\\hateemel\\projects\\node\\patron-helper\\node_modules\\regenerator-runtime\\runtime.js:145:13"}
